// cancion.js - Datos de la letra de la canción con tiempos en segundos
const lyricsData = [
    { time: 0.0, text: "..." },
    { time: 17.0, text: "Él la estaba esperando con una flor amarilla" },
    { time: 25.5, text: "Ella lo estaba soñando con la luz en su pupila" },
    { time: 32.0, text: "Y el amarillo del sol iluminaba la esquina (la esquina)" },
    { time: 41.0, text: "Lo sentía tan cercano, lo sentía desde niña" },
    { time: 46.0, text: "Ella sabía que él sabía, que algún día pasaría" },
    { time: 52.0, text: "Que vendría a buscarla, con sus flores amarillas" },
    { time: 60.0, text: "No te apures no detengas, el instante del encuentro" },
    { time: 64.0, text: "Está dicho que es un hecho, no la pierdas no hay derecho" },
    { time: 67.0, text: "No te olvides, que la vida casi nunca está dormida" },
    { time: 94.0, text: "En ese bar tan desierto los esperaba el encuentro (el encuentro)" },
    { time: 102.0, text: "Ella llegó en limosina amarilla por supuesto" },
    { time: 110.0, text: "Él se acercó de repente y la miró tan de frente (de frente)" },
    { time: 118.0, text: "Toda una vida soñada y no pudo decir nada" },
    { time: 124.0, text: "Ella sabía que él sabía, que algún día pasaría" },
    { time: 129.0, text: "Que vendría a buscarla, con sus flores amarillas" },
    { time: 137.0, text: "No te apures no detengas, el instante del encuentro" },
    { time: 141.0, text: "Está dicho que es un hecho, no la pierdas no hay derecho" },
    { time: 145.0, text: "No te olvides, que la vida casi nunca está dormida" },
    { time: 161.0, text: "Flores amarillas" },
    { time: 169.0, text: "Ella sabía que él sabía, que algún día pasaría" },
    { time: 174.0, text: "Que vendría a buscarla, con sus flores amarillas" },
    { time: 182.0, text: "No te apures no detengas, el instante del encuentro" },
    { time: 186.0, text: "Está dicho que es un hecho, no la pierdas no hay derecho" },
    { time: 190.0, text: "No te olvides, que la vida casi nunca está dormida" },
    { time: 198.0, text: "Ella sabía que él sabía" },
    { time: 202.0, text: "Él sabía, ella sabia" },
    { time: 204.0, text: "Él sabía, ella sabía" },
    { time: 206.0, text: "Y se olvidaron,de sus flores amarillas" },
];